#!/bin/sh

for i in *.c src/*.c utils/*.c ; do
  if test -f $i; then
    echo Reformatting $i
    indent -bap -br -ce -ci4 -cli2 -cs -di1 -i4 -l140 -lp -lps -nbc -npcs -nss -nsob -psl $i
  fi
done

perl -p -i.bak -e 's/(\w+)_t (\*+)\s+/$1_t $2/g;' */*.[ch]
