.TH ETERM-UTILS 1
.SH NAME
eterm-utils \- Eterm accessory programs
.SH SYNOPSIS
.B  Esetroot
.I "[-display display] [-scale] pixmap"
.br
.B kEsetroot
.I pixmap
.br
.B Etbg
.I "pixmap"
.br
.B Ettable
.br
.B Etcolors
.br
.B Etsearch
.I string
.br
.B Etbg_update_list
.SH "DESCRIPTION"
.PP
.B Esetroot
set the Eterm background for transparency with window managers other than enlightenment.
.B kEsetroot 
is provided for KDE. 
.br
.B Etbg
set the Eterm background image
.br
.B Ettable
display the current font character set
.br
.B Etcolors
display a table of the current color map
.br 
.B Etsearch
search the scroll back buffer, it's secksie
.br
.B Etbg_update_list
update pixmap lists for the menus
.SH "SEE ALSO"
.IR "eterm(1)" ,
.SH AUTHOR
This manual page was written by Laurence J. Lane <ljlane@debian.org>,
for the Debian GNU/Linux system (but may be used by others).
