#!/bin/sh -e

BIN=/usr/bin/Eterm

if [ "$1" = configure ]; then
   ldconfig
   if test -x /usr/bin/update-menus; then update-menus; fi
   if test -e /etc/suid.conf -a -x /usr/sbin/suidregister; then
      #cleanup old "Eterm" mess
      if test -x /usr/sbin/suidunregister; then
         grep -q "Eterm $BIN" /etc/suid.conf && /usr/sbin/suidunregister -s Eterm $BIN
      fi
      suidregister -s eterm /usr/bin/Eterm root utmp 2755
    else
        chown root.utmp $BIN
        chmod 2755 $BIN
    fi
fi

#DEBHELPER#
